name: Generate Snake Animation

on:
  schedule: 
    - cron: "0 5 * * *"  # Runs every day at 05:00 UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Generate the snake animation SVG
      - name: Generate snake.svg
        uses: Platane/snk@master
        with:
          github_user_name: shaansuraj

      # Debugging step to list files
      - name: List files in the working directory
        run: ls -alh

      # Debugging step to check if the SVG is generated
      - name: Check if SVG is generated
        run: |
          if [ -f github-contribution-grid-snake.svg ]; then
            echo "SVG generated successfully."
          else
            echo "SVG not found!"
            exit 1
          fi

      # Commit and push the generated SVG to a specific branch or location
      - name: Commit and Push SVG
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add github-contribution-grid-snake.svg
          git commit -m "Update snake.svg"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}