name: Generate Snake Animation

on:
  schedule: 
    - cron: "0 5 * * *"  # Runs every day at 05:00 UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: main  

      # Generate the snake animation SVG and output it in the repository root
      - name: Generate snake.svg
        uses: Platane/snk@master
        with:
          github_user_name: shaansuraj
          svg_out_path: github-contribution-grid-snake.svg

      # Debug: List all SVG files to verify the output location
      - name: Find SVG Files
        run: find . -type f -name "*.svg"

      # Commit and push the generated SVG to the repository
      - name: Commit and Push SVG
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add github-contribution-grid-snake.svg
          git commit -m "Update snake.svg"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
